/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PluginAudioProcessorEditor_H_6F2C751__
#define __PluginAudioProcessorEditor_H_6F2C751__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "PluginAudioProcessor.h"


//==============================================================================
/**
*/
class PluginAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    PluginAudioProcessorEditor (PluginAudioProcessor* ownerFilter);
    ~PluginAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PluginAudioProcessorEditor_H_6F2C751__
