/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_6F2C751__
#define __PLUGINEDITOR_H_6F2C751__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class PluginTemplate1AudioProcessorEditor  : public AudioProcessorEditor
{
public:
    PluginTemplate1AudioProcessorEditor (PluginTemplate1AudioProcessor* ownerFilter);
    ~PluginTemplate1AudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_6F2C751__
